# Generated by Django 3.1.2 on 2020-12-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20201201_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='image', upload_to='', verbose_name='Обложка книги'),
        ),
    ]
